### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by degerahmet** [scistone/scistone-react-components#4]
Form

- [ ] Sample Login Form
- [ ] Sample Address Form
- [ ] Sample Register Form
- [ ] Sample Contact Form
- [ ] Sample Password Change Form

-------------------------------------------------------------

Menu

- [ ] Create primary and secondary CSS styles for the Menu component.
- [ ] Add Primary and secondary CSS styles in the Menu component.
- [ ] Check the subItems exist for the subItems map function.
- [ ] Add dynamic underline color for the menu title area.

-------------------------------------------------------------

Drawer

- [ ] Add animation to the Drawer in and out.

**Comment by degerahmet** [comment]
Menu

- [ ] Create primary and secondary CSS styles for the Menu component.
- [ ] Add Primary and secondary CSS styles in the Menu component.
- [ ] Check the subItems exist for the subItems map function.
- [ ] Add dynamic underline color for the menu title area.
